// interfaces exports
export type { ICharacter } from './interfaces/character/ICharacter'
export type { IAttributeOwner } from './interfaces/character/IAttributeOwner'
export type { IEffectOwner } from './interfaces/character/IEffectOwner'
export type { ICombatContext } from './interfaces/context/ICombatContext'
export type { CombatConfig } from './interfaces/combat-engine/CombatConfig'
export type { CombatResult } from './interfaces/combat-engine/CombatResult'
export type { CombatResultData } from './interfaces/combat-engine/CombatResultData'
export type { CombatSnapshot } from './interfaces/combat-engine/CombatSnapshot'
export type { CharacterSnapshot } from './interfaces/shared/CharacterSnapshot'
export type { CombatLogEntry } from './interfaces/logger/CombatLogEntry'
export type { DamageEvent } from './interfaces/damage/DamageEvent'
export type { ICombatHook } from './interfaces/damage/ICombatHook'
export { CombatError } from './interfaces/errors/CombatError'
export { CombatFailureCode } from './interfaces/errors/CombatFailure'
export type { IUltimateAbility } from './interfaces/ultimate/IUltimateAbility'
export type { IResourceRegistry } from './interfaces/resource-registry/IResourceRegistry'

// domain exports
export { CombatTiming, CombatSystem, UltimateEnergy } from './domain/config/CombatConstants'
export { UltimateDefaults } from './domain/config/UltimateConstants'
export { EffectNames } from './domain/config/EffectConstants'

// app exports
export { CombatEngine } from './app/combat-engine/CombatEngine'
export { Character } from './app/character/Character'
export { FirstAliveSelector } from './domain/target-select-strategies/FirstAliveSelector'
export { CharacterAccessor } from './app/shared/utils/CharacterAccessor'
export { DamageChain } from './app/damage/DamageChain'
export { DamageFactory } from './app/coordination/utils/DamageFactory'
export { createDefaultDamageSteps } from './app/damage/DefaultDamageSteps'
